[Los Alamos Daily Post]
# url = http://www.ladailypost.com/feed/
url = http://www.ladailypost.com/search/?f=rss&t=article&c=&l=50&s=start_time&sd=desc
page_start = id="article-body" itemprop="articleBody"
page_end = id="tncms-region-article_instory_bottom"
	id="tncms-region-article_bottom_content"

# LADP is now blacklisting hosts for fetching too many URLs.
# Fetching images can trigger that, so turn them off.
skip_images = true
# nonlocal_images = true

user_agent = Mozilla/5.0 (X11; Linux x86_64; rv:156.0) Gecko/20100101 Firefox/156.0

# allow_gzip = false
simplify_rss = true
rss_entry_size = 1000

# max_image_size needs to be set in order to rewrite png to jpg
# to reduce download size. It doesn't matter what pixel size it's set to,
# so if you don't want image resizing, set it to a larger number.
max_image_size = 1024

# feedme has logic to convert PNGs if they're not transparent,
# but LADP makes even some of their photo images transparent.
png_to_jpg = true

